version: "3.9"
services:
  jupyterlab:
    container_name: jupyterlab
    image: jupyter/tensorflow-notebook:latest
    restart: unless-stopped
    # Password is 'jupyterlab'
    # Start the service for the first time. 
    # Then stop the container and restart it after uncommenting the following line.
    # entrypoint: start-notebook.sh --NotebookApp.password='sha1:eaccb17f0bfa:3894d6bb2ff94c757ee358a3107e75e034ec061f'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    expose:
      - "9010"
    ports:
      - "9010:8888"
    volumes:
      - '~/Arena/jupyterlab:/home/jovyan'
